spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:local;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: true

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type: INFO





