spring:
  datasource:
    url: jdbc:log4jdbc:mysql://mysql:3306/board?cacheServerConfiguration=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: board
    password: board
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  redis:
    host: redis
#  kafka:
#    bootstrap-servers: kafka1:9092,kafka2:9093,kafka3:9094

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type: INFO
    log4jdbc:
      log4j2: WARN